name: Build GitHub Pages
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  deploy:
    uses: OWASP/mas-website/.github/workflows/build-website-reusable.yml@main
    with:
      deploy: true
    secrets: inherit
    if: github.actor == 'cpholguera' || github.actor == 'sushi2k' || github.actor == 'TheDauntless'