name: Check Website Build
on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: OWASP/mas-website/.github/workflows/build-website-reusable.yml@main
    with:
      deploy: false
      sources_override_json: ${{ toJson(fromJson(format('{{"{0}":"{1}"}'} , github.event.pull_request.head.repo.full_name, github.event.pull_request.head.ref))) }}
